name: Publish tag to Pypi

on:
  release:
    types: [published]

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:

  build_and_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Build the package
        run: |
          poetry build

      - name: Basic package test prior to upload
        run: |
          twine check dist/*

      - name: Publish to Pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
